spring.datasource.url=jdbc:mysql://172.16.0.30:3306/elr_osapi?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=elr
spring.datasource.password=gmSenai
spring.jpa.show-sql=True

logging.level.org.springframework.web=DEBUG

